import 'package:freezed_annotation/freezed_annotation.dart';

part 'planned_session.freezed.dart';
part 'planned_session.g.dart';

/// A single session within a DailyPlan, selected by the bandit engine.
///
/// [sessionType]: 'mobility' | 'cardio' | 'breathing' — matches Sessions DB table.
/// [intensity]:   1–10 — maps to SessionIntensity enum for safety rule checking.
/// [durationMinutes]: from exercise catalog (populated in Story 6.x).
/// [isIndoor]:    true when SafetyConstraints.outdoorAllowed = false, or
///                user physicalConstraints = 'indoor'.
/// [explanation]: generated by ExplanationGenerator (Story 5.6).
///   Empty string '' is the placeholder — Story 5.6 guarantees non-empty on write.
@freezed
abstract class PlannedSession with _$PlannedSession {
  const factory PlannedSession({
    required String sessionType,
    required int intensity,
    required int durationMinutes,
    required bool isIndoor,
    @Default('') String explanation,
  }) = _PlannedSession;

  factory PlannedSession.fromJson(Map<String, dynamic> json) =>
      _$PlannedSessionFromJson(json);
}
