// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/data/repositories/exercise_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pulse_coach/features/sessions_catalog/data/datasources/exercise_local_data_source.dart'
    as _i5;
import 'package:pulse_coach/features/sessions_catalog/data/datasources/exercise_remote_data_source.dart'
    as _i2;
import 'package:pulse_coach/features/sessions_catalog/data/models/exercise_model.dart'
    as _i4;
import 'package:pulse_coach/features/sessions_catalog/domain/entities/exercise.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ExerciseRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRemoteDataSource extends _i1.Mock
    implements _i2.ExerciseRemoteDataSource {
  MockExerciseRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ExerciseModel>> fetchAll() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAll, []),
            returnValue: _i3.Future<List<_i4.ExerciseModel>>.value(
              <_i4.ExerciseModel>[],
            ),
          )
          as _i3.Future<List<_i4.ExerciseModel>>);

  @override
  _i3.Future<List<_i4.ExerciseModel>> fetchExercisesByType(
    String? sessionType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchExercisesByType, [sessionType]),
            returnValue: _i3.Future<List<_i4.ExerciseModel>>.value(
              <_i4.ExerciseModel>[],
            ),
          )
          as _i3.Future<List<_i4.ExerciseModel>>);
}

/// A class which mocks [ExerciseLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseLocalDataSource extends _i1.Mock
    implements _i5.ExerciseLocalDataSource {
  MockExerciseLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i5.CachedExerciseEntry>> getCachedExercisesByType(
    String? sessionType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedExercisesByType, [sessionType]),
            returnValue: _i3.Future<List<_i5.CachedExerciseEntry>>.value(
              <_i5.CachedExerciseEntry>[],
            ),
          )
          as _i3.Future<List<_i5.CachedExerciseEntry>>);

  @override
  _i3.Future<void> cacheExercises(
    List<_i6.Exercise>? exercises,
    DateTime? cachedAt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheExercises, [exercises, cachedAt]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> replaceCache(
    List<_i6.Exercise>? exercises,
    DateTime? cachedAt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#replaceCache, [exercises, cachedAt]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.Exercise>> loadFallbackExercisesByType(
    String? sessionType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadFallbackExercisesByType, [sessionType]),
            returnValue: _i3.Future<List<_i6.Exercise>>.value(<_i6.Exercise>[]),
          )
          as _i3.Future<List<_i6.Exercise>>);
}
