// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/data/repositories/weather_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pulse_coach/core/error/failures.dart' as _i10;
import 'package:pulse_coach/core/utils/location_service.dart' as _i9;
import 'package:pulse_coach/features/weather/data/datasources/weather_local_data_source.dart'
    as _i7;
import 'package:pulse_coach/features/weather/data/datasources/weather_remote_data_source.dart'
    as _i5;
import 'package:pulse_coach/features/weather/data/models/aqi_model.dart' as _i3;
import 'package:pulse_coach/features/weather/data/models/weather_model.dart'
    as _i2;
import 'package:pulse_coach/features/weather/domain/entities/weather_context.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWeatherModel_0 extends _i1.SmartFake implements _i2.WeatherModel {
  _FakeWeatherModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAqiModel_1 extends _i1.SmartFake implements _i3.AqiModel {
  _FakeAqiModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WeatherRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDataSource extends _i1.Mock
    implements _i5.WeatherRemoteDataSource {
  MockWeatherRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<(_i2.WeatherModel, _i3.AqiModel)> fetchWeatherAndAqi({
    required double? latitude,
    required double? longitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWeatherAndAqi, [], {
              #latitude: latitude,
              #longitude: longitude,
            }),
            returnValue: _i6.Future<(_i2.WeatherModel, _i3.AqiModel)>.value((
              _FakeWeatherModel_0(
                this,
                Invocation.method(#fetchWeatherAndAqi, [], {
                  #latitude: latitude,
                  #longitude: longitude,
                }),
              ),
              _FakeAqiModel_1(
                this,
                Invocation.method(#fetchWeatherAndAqi, [], {
                  #latitude: latitude,
                  #longitude: longitude,
                }),
              ),
            )),
          )
          as _i6.Future<(_i2.WeatherModel, _i3.AqiModel)>);
}

/// A class which mocks [WeatherLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherLocalDataSource extends _i1.Mock
    implements _i7.WeatherLocalDataSource {
  MockWeatherLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i8.WeatherContext?> getCachedWeather() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedWeather, []),
            returnValue: _i6.Future<_i8.WeatherContext?>.value(),
          )
          as _i6.Future<_i8.WeatherContext?>);

  @override
  _i6.Future<void> cacheWeather({
    required double? latitude,
    required double? longitude,
    required double? temperature,
    required double? precipitationProbability,
    required int? aqiValue,
    required DateTime? cachedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cacheWeather, [], {
              #latitude: latitude,
              #longitude: longitude,
              #temperature: temperature,
              #precipitationProbability: precipitationProbability,
              #aqiValue: aqiValue,
              #cachedAt: cachedAt,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i9.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Either<_i10.Failure, (double, double)>>
  getCityLevelCoordinates() =>
      (super.noSuchMethod(
            Invocation.method(#getCityLevelCoordinates, []),
            returnValue:
                _i6.Future<_i4.Either<_i10.Failure, (double, double)>>.value(
                  _FakeEither_2<_i10.Failure, (double, double)>(
                    this,
                    Invocation.method(#getCityLevelCoordinates, []),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i10.Failure, (double, double)>>);
}
