// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/data/auth/backup_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i7;

import 'package:connectivity_plus/connectivity_plus.dart' as _i8;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pulse_coach/core/cloud/crypto/backup_envelope.dart' as _i2;
import 'package:pulse_coach/core/cloud/crypto/e2e_backup_codec.dart' as _i6;
import 'package:pulse_coach/features/auth/data/datasources/backup_local_data_source.dart'
    as _i5;
import 'package:pulse_coach/features/auth/data/datasources/backup_remote_data_source.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBackupEnvelope_0 extends _i1.SmartFake
    implements _i2.BackupEnvelope {
  _FakeBackupEnvelope_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BackupRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupRemoteDataSource extends _i1.Mock
    implements _i3.BackupRemoteDataSource {
  MockBackupRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> uploadBackup({
    required String? userId,
    required _i2.BackupEnvelope? envelope,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadBackup, [], {
              #userId: userId,
              #envelope: envelope,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.BackupEnvelope> downloadBackup({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#downloadBackup, [], {#userId: userId}),
            returnValue: _i4.Future<_i2.BackupEnvelope>.value(
              _FakeBackupEnvelope_0(
                this,
                Invocation.method(#downloadBackup, [], {#userId: userId}),
              ),
            ),
          )
          as _i4.Future<_i2.BackupEnvelope>);
}

/// A class which mocks [BackupLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupLocalDataSource extends _i1.Mock
    implements _i5.BackupLocalDataSource {
  MockBackupLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<String, dynamic>> exportDriftSnapshot() =>
      (super.noSuchMethod(
            Invocation.method(#exportDriftSnapshot, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> restoreDriftSnapshot(Map<String, dynamic>? snapshot) =>
      (super.noSuchMethod(
            Invocation.method(#restoreDriftSnapshot, [snapshot]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> storeEncryptionKey(String? base64Key) =>
      (super.noSuchMethod(
            Invocation.method(#storeEncryptionKey, [base64Key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> loadEncryptionKey() =>
      (super.noSuchMethod(
            Invocation.method(#loadEncryptionKey, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> setBackupEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setBackupEnabled, [enabled]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> loadBackupEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#loadBackupEnabled, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> queueBackupTask({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#queueBackupTask, [], {#userId: userId}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [E2eBackupCodec].
///
/// See the documentation for Mockito's code generation for more information.
class MockE2eBackupCodec extends _i1.Mock implements _i6.E2eBackupCodec {
  MockE2eBackupCodec() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BackupEnvelope> encrypt({
    required String? passphrase,
    required Map<String, dynamic>? payload,
    _i7.Uint8List? saltOverride,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#encrypt, [], {
              #passphrase: passphrase,
              #payload: payload,
              #saltOverride: saltOverride,
            }),
            returnValue: _i4.Future<_i2.BackupEnvelope>.value(
              _FakeBackupEnvelope_0(
                this,
                Invocation.method(#encrypt, [], {
                  #passphrase: passphrase,
                  #payload: payload,
                  #saltOverride: saltOverride,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.BackupEnvelope>);

  @override
  _i4.Future<Map<String, dynamic>> decrypt({
    required String? passphrase,
    required _i2.BackupEnvelope? envelope,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decrypt, [], {
              #passphrase: passphrase,
              #envelope: envelope,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i8.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i9.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i4.Stream<List<_i9.ConnectivityResult>>.empty(),
          )
          as _i4.Stream<List<_i9.ConnectivityResult>>);

  @override
  _i4.Future<List<_i9.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i4.Future<List<_i9.ConnectivityResult>>.value(
              <_i9.ConnectivityResult>[],
            ),
          )
          as _i4.Future<List<_i9.ConnectivityResult>>);
}
