include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_slow_async_io
    - avoid_unnecessary_containers
    - avoid_void_async
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - require_trailing_commas
    - sized_box_for_whitespace
    - use_key_in_widget_constructors

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning
