// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/data/social/feed_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:pulse_coach/features/social/feed/data/datasources/feed_remote_data_source.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FeedRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedRemoteDataSource extends _i1.Mock
    implements _i2.FeedRemoteDataSource {
  MockFeedRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> Function(Map<String, dynamic>) get insertFeedEntry =>
      (super.noSuchMethod(
            Invocation.getter(#insertFeedEntry),
            returnValue: (Map<String, dynamic> row) => _i3.Future<void>.value(),
          )
          as _i3.Future<void> Function(Map<String, dynamic>));

  @override
  _i3.Future<List<Map<String, dynamic>>> Function() get fetchFeed =>
      (super.noSuchMethod(
            Invocation.getter(#fetchFeed),
            returnValue: () => _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>> Function());

  @override
  _i3.Future<void> Function(String) get callIncrementReaction =>
      (super.noSuchMethod(
            Invocation.getter(#callIncrementReaction),
            returnValue: (String feedEntryId) => _i3.Future<void>.value(),
          )
          as _i3.Future<void> Function(String));

  @override
  _i3.Future<void> Function(String) get deleteFeedEntry =>
      (super.noSuchMethod(
            Invocation.getter(#deleteFeedEntry),
            returnValue: (String feedEntryId) => _i3.Future<void>.value(),
          )
          as _i3.Future<void> Function(String));

  @override
  String get currentUserId =>
      (super.noSuchMethod(
            Invocation.getter(#currentUserId),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#currentUserId),
            ),
          )
          as String);

  @override
  set insertFeedEntry(_i3.Future<void> Function(Map<String, dynamic>)? value) =>
      super.noSuchMethod(
        Invocation.setter(#insertFeedEntry, value),
        returnValueForMissingStub: null,
      );

  @override
  set fetchFeed(_i3.Future<List<Map<String, dynamic>>> Function()? value) =>
      super.noSuchMethod(
        Invocation.setter(#fetchFeed, value),
        returnValueForMissingStub: null,
      );

  @override
  set callIncrementReaction(_i3.Future<void> Function(String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#callIncrementReaction, value),
        returnValueForMissingStub: null,
      );

  @override
  set deleteFeedEntry(_i3.Future<void> Function(String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#deleteFeedEntry, value),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> share({
    required String? ownerId,
    required String? sessionType,
    required int? durationMinutes,
    required DateTime? completedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#share, [], {
              #ownerId: ownerId,
              #sessionType: sessionType,
              #durationMinutes: durationMinutes,
              #completedAt: completedAt,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> loadFeed() =>
      (super.noSuchMethod(
            Invocation.method(#loadFeed, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> incrementReaction(String? feedEntryId) =>
      (super.noSuchMethod(
            Invocation.method(#incrementReaction, [feedEntryId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> revoke(String? feedEntryId) =>
      (super.noSuchMethod(
            Invocation.method(#revoke, [feedEntryId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
