// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/data/social/friends_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pulse_coach/features/social/friends/data/datasources/friends_remote_data_source.dart'
    as _i2;
import 'package:pulse_coach/features/social/friends/data/models/social_profile_dto.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FriendsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFriendsRemoteDataSource extends _i1.Mock
    implements _i2.FriendsRemoteDataSource {
  MockFriendsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>?> Function(String) get searchByHandle =>
      (super.noSuchMethod(
            Invocation.getter(#searchByHandle),
            returnValue: (String handle) =>
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?> Function(String));

  @override
  _i3.Future<Map<String, List<Map<String, dynamic>>>> Function()
  get fetchPendingRequests =>
      (super.noSuchMethod(
            Invocation.getter(#fetchPendingRequests),
            returnValue: () =>
                _i3.Future<Map<String, List<Map<String, dynamic>>>>.value(
                  <String, List<Map<String, dynamic>>>{},
                ),
          )
          as _i3.Future<Map<String, List<Map<String, dynamic>>>> Function());

  @override
  _i3.Future<List<Map<String, dynamic>>> Function() get fetchFriends =>
      (super.noSuchMethod(
            Invocation.getter(#fetchFriends),
            returnValue: () => _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>> Function());

  @override
  _i3.Future<void> Function(String) get insertFriendRequest =>
      (super.noSuchMethod(
            Invocation.getter(#insertFriendRequest),
            returnValue: (String addresseeId) => _i3.Future<void>.value(),
          )
          as _i3.Future<void> Function(String));

  @override
  _i3.Future<void> Function(String, String) get updateFriendshipStatus =>
      (super.noSuchMethod(
            Invocation.getter(#updateFriendshipStatus),
            returnValue: (String friendshipId, String status) =>
                _i3.Future<void>.value(),
          )
          as _i3.Future<void> Function(String, String));

  @override
  _i3.Future<void> Function(String) get deleteFriendship =>
      (super.noSuchMethod(
            Invocation.getter(#deleteFriendship),
            returnValue: (String friendshipId) => _i3.Future<void>.value(),
          )
          as _i3.Future<void> Function(String));

  @override
  set searchByHandle(
    _i3.Future<Map<String, dynamic>?> Function(String)? value,
  ) => super.noSuchMethod(
    Invocation.setter(#searchByHandle, value),
    returnValueForMissingStub: null,
  );

  @override
  set fetchPendingRequests(
    _i3.Future<Map<String, List<Map<String, dynamic>>>> Function()? value,
  ) => super.noSuchMethod(
    Invocation.setter(#fetchPendingRequests, value),
    returnValueForMissingStub: null,
  );

  @override
  set fetchFriends(_i3.Future<List<Map<String, dynamic>>> Function()? value) =>
      super.noSuchMethod(
        Invocation.setter(#fetchFriends, value),
        returnValueForMissingStub: null,
      );

  @override
  set insertFriendRequest(_i3.Future<void> Function(String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#insertFriendRequest, value),
        returnValueForMissingStub: null,
      );

  @override
  set updateFriendshipStatus(
    _i3.Future<void> Function(String, String)? value,
  ) => super.noSuchMethod(
    Invocation.setter(#updateFriendshipStatus, value),
    returnValueForMissingStub: null,
  );

  @override
  set deleteFriendship(_i3.Future<void> Function(String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#deleteFriendship, value),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<_i4.SocialProfileDto?> findByHandle(String? handle) =>
      (super.noSuchMethod(
            Invocation.method(#findByHandle, [handle]),
            returnValue: _i3.Future<_i4.SocialProfileDto?>.value(),
          )
          as _i3.Future<_i4.SocialProfileDto?>);

  @override
  _i3.Future<
    ({List<Map<String, dynamic>> received, List<Map<String, dynamic>> sent})
  >
  getPendingRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingRequests, []),
            returnValue:
                _i3.Future<
                  ({
                    List<Map<String, dynamic>> received,
                    List<Map<String, dynamic>> sent,
                  })
                >.value((
                  received: <Map<String, dynamic>>[],
                  sent: <Map<String, dynamic>>[],
                )),
          )
          as _i3.Future<
            ({
              List<Map<String, dynamic>> received,
              List<Map<String, dynamic>> sent,
            })
          >);

  @override
  _i3.Future<List<Map<String, dynamic>>> getAllFriends() =>
      (super.noSuchMethod(
            Invocation.method(#getAllFriends, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> addFriend(String? addresseeId) =>
      (super.noSuchMethod(
            Invocation.method(#addFriend, [addresseeId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> acceptFriendship(String? friendshipId) =>
      (super.noSuchMethod(
            Invocation.method(#acceptFriendship, [friendshipId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> declineFriendship(String? friendshipId) =>
      (super.noSuchMethod(
            Invocation.method(#declineFriendship, [friendshipId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeFriendship(String? friendshipId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFriendship, [friendshipId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
