// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/data/social/progress_comparison_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pulse_coach/features/social/comparison/data/datasources/progress_comparison_remote_data_source.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProgressComparisonRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgressComparisonRemoteDataSource extends _i1.Mock
    implements _i2.ProgressComparisonRemoteDataSource {
  MockProgressComparisonRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<Map<String, dynamic>>> Function() get fetchFriendsProgress =>
      (super.noSuchMethod(
            Invocation.getter(#fetchFriendsProgress),
            returnValue: () => _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>> Function());

  @override
  set fetchFriendsProgress(
    _i3.Future<List<Map<String, dynamic>>> Function()? value,
  ) => super.noSuchMethod(
    Invocation.setter(#fetchFriendsProgress, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<List<Map<String, dynamic>>> loadFriendsProgress() =>
      (super.noSuchMethod(
            Invocation.method(#loadFriendsProgress, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);
}
