// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/data/social/shared_session_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:pulse_coach/features/social/shared_session/data/datasources/shared_session_remote_data_source.dart'
    as _i3;
import 'package:pulse_coach/features/social/shared_session/data/models/shared_session_dto.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSharedSessionDto_0 extends _i1.SmartFake
    implements _i2.SharedSessionDto {
  _FakeSharedSessionDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SharedSessionRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedSessionRemoteDataSource extends _i1.Mock
    implements _i3.SharedSessionRemoteDataSource {
  MockSharedSessionRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SharedSessionDto> createSharedSession({
    required String? hostUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSharedSession, [], {
              #hostUserId: hostUserId,
            }),
            returnValue: _i4.Future<_i2.SharedSessionDto>.value(
              _FakeSharedSessionDto_0(
                this,
                Invocation.method(#createSharedSession, [], {
                  #hostUserId: hostUserId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.SharedSessionDto>);

  @override
  _i4.Future<String> refreshJoinCode({required String? sessionId}) =>
      (super.noSuchMethod(
            Invocation.method(#refreshJoinCode, [], {#sessionId: sessionId}),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#refreshJoinCode, [], {
                  #sessionId: sessionId,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> deleteSharedSession({required String? sessionId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSharedSession, [], {
              #sessionId: sessionId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.SharedSessionDto> joinSharedSession({
    required String? joinCode,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinSharedSession, [], {
              #joinCode: joinCode,
              #userId: userId,
            }),
            returnValue: _i4.Future<_i2.SharedSessionDto>.value(
              _FakeSharedSessionDto_0(
                this,
                Invocation.method(#joinSharedSession, [], {
                  #joinCode: joinCode,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.SharedSessionDto>);
}
