// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/data/social/social_profile_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pulse_coach/features/social/friends/data/datasources/social_profile_remote_data_source.dart'
    as _i3;
import 'package:pulse_coach/features/social/friends/data/models/social_profile_dto.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSocialProfileDto_0 extends _i1.SmartFake
    implements _i2.SocialProfileDto {
  _FakeSocialProfileDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SocialProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialProfileRemoteDataSource extends _i1.Mock
    implements _i3.SocialProfileRemoteDataSource {
  MockSocialProfileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<String, dynamic>?> Function() get fetchProfile =>
      (super.noSuchMethod(
            Invocation.getter(#fetchProfile),
            returnValue: () => _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?> Function());

  @override
  _i4.Future<Map<String, dynamic>> Function(Map<String, dynamic>)
  get patchProfile =>
      (super.noSuchMethod(
            Invocation.getter(#patchProfile),
            returnValue: (Map<String, dynamic> patch) =>
                _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
          )
          as _i4.Future<Map<String, dynamic>> Function(Map<String, dynamic>));

  @override
  set fetchProfile(_i4.Future<Map<String, dynamic>?> Function()? value) =>
      super.noSuchMethod(
        Invocation.setter(#fetchProfile, value),
        returnValueForMissingStub: null,
      );

  @override
  set patchProfile(
    _i4.Future<Map<String, dynamic>> Function(Map<String, dynamic>)? value,
  ) => super.noSuchMethod(
    Invocation.setter(#patchProfile, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i2.SocialProfileDto> getSocialProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getSocialProfile, []),
            returnValue: _i4.Future<_i2.SocialProfileDto>.value(
              _FakeSocialProfileDto_0(
                this,
                Invocation.method(#getSocialProfile, []),
              ),
            ),
          )
          as _i4.Future<_i2.SocialProfileDto>);

  @override
  _i4.Future<_i2.SocialProfileDto> updateHandle(String? handle) =>
      (super.noSuchMethod(
            Invocation.method(#updateHandle, [handle]),
            returnValue: _i4.Future<_i2.SocialProfileDto>.value(
              _FakeSocialProfileDto_0(
                this,
                Invocation.method(#updateHandle, [handle]),
              ),
            ),
          )
          as _i4.Future<_i2.SocialProfileDto>);

  @override
  _i4.Future<_i2.SocialProfileDto> updateVisibilityTier(
    String? supabaseValue,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateVisibilityTier, [supabaseValue]),
            returnValue: _i4.Future<_i2.SocialProfileDto>.value(
              _FakeSocialProfileDto_0(
                this,
                Invocation.method(#updateVisibilityTier, [supabaseValue]),
              ),
            ),
          )
          as _i4.Future<_i2.SocialProfileDto>);
}
