// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/widget/device_settings_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_bloc/flutter_bloc.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pulse_coach/features/settings/presentation/bloc/device_settings_cubit.dart'
    as _i3;
import 'package:pulse_coach/features/settings/presentation/bloc/device_settings_state.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDeviceSettingsState_0 extends _i1.SmartFake
    implements _i2.DeviceSettingsState {
  _FakeDeviceSettingsState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DeviceSettingsCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceSettingsCubit extends _i1.Mock
    implements _i3.DeviceSettingsCubit {
  MockDeviceSettingsCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DeviceSettingsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeDeviceSettingsState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.DeviceSettingsState);

  @override
  _i4.Stream<_i2.DeviceSettingsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i2.DeviceSettingsState>.empty(),
          )
          as _i4.Stream<_i2.DeviceSettingsState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i4.Future<void> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> requestHealthPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestHealthPermission, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> syncNow() =>
      (super.noSuchMethod(
            Invocation.method(#syncNow, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void emit(_i2.DeviceSettingsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i5.Change<_i2.DeviceSettingsState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
