// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/features/auth/auth_repository_impl_sync_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:pulse_coach/core/cloud/supabase_client.dart' as _i7;
import 'package:pulse_coach/features/auth/data/datasources/auth_remote_data_source.dart'
    as _i4;
import 'package:pulse_coach/features/auth/domain/entities/auth_user.dart'
    as _i2;
import 'package:supabase_flutter/supabase_flutter.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthUser_0 extends _i1.SmartFake implements _i2.AuthUser {
  _FakeAuthUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseClient_1 extends _i1.SmartFake
    implements _i3.SupabaseClient {
  _FakeSupabaseClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i4.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AuthUser> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i5.Future<_i2.AuthUser>.value(
              _FakeAuthUser_0(this, Invocation.method(#signInWithApple, [])),
            ),
          )
          as _i5.Future<_i2.AuthUser>);

  @override
  _i5.Future<_i2.AuthUser> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i5.Future<_i2.AuthUser>.value(
              _FakeAuthUser_0(this, Invocation.method(#signInWithGoogle, [])),
            ),
          )
          as _i5.Future<_i2.AuthUser>);

  @override
  _i5.Future<_i2.AuthUser> signInWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i2.AuthUser>.value(
              _FakeAuthUser_0(
                this,
                Invocation.method(#signInWithEmail, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthUser>);

  @override
  _i5.Future<_i2.AuthUser?> signUp({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i2.AuthUser?>.value(),
          )
          as _i5.Future<_i2.AuthUser?>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> exportData() =>
      (super.noSuchMethod(
            Invocation.method(#exportData, []),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(this, Invocation.method(#exportData, [])),
            ),
          )
          as _i5.Future<String>);
}

/// A class which mocks [SupabaseClientProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClientProvider extends _i1.Mock
    implements _i7.SupabaseClientProvider {
  MockSupabaseClientProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SupabaseClient get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeSupabaseClient_1(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i3.SupabaseClient);
}
