// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/widget/progress/progress_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pulse_coach/core/error/failures.dart' as _i5;
import 'package:pulse_coach/features/progress/domain/entities/progress_stats.dart'
    as _i8;
import 'package:pulse_coach/features/progress/domain/entities/session_history_entry.dart'
    as _i6;
import 'package:pulse_coach/features/progress/domain/usecases/get_progress_stats.dart'
    as _i7;
import 'package:pulse_coach/features/progress/domain/usecases/get_session_history.dart'
    as _i3;
import 'package:pulse_coach/features/subscription/domain/entities/subscription_tier.dart'
    as _i11;
import 'package:pulse_coach/features/subscription/domain/usecases/check_entitlement_use_case.dart'
    as _i10;
import 'package:pulse_coach/features/subscription/domain/usecases/get_install_cohort_use_case.dart'
    as _i9;
import 'package:pulse_coach/features/subscription/domain/usecases/purchase_pro_use_case.dart'
    as _i12;
import 'package:pulse_coach/features/subscription/domain/usecases/restore_purchases_use_case.dart'
    as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetSessionHistory].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSessionHistory extends _i1.Mock implements _i3.GetSessionHistory {
  MockGetSessionHistory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.SessionHistoryEntry>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.SessionHistoryEntry>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.SessionHistoryEntry>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.Failure, List<_i6.SessionHistoryEntry>>
          >);
}

/// A class which mocks [GetProgressStats].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProgressStats extends _i1.Mock implements _i7.GetProgressStats {
  MockGetProgressStats() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.ProgressStats>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i8.ProgressStats>>.value(
                  _FakeEither_0<_i5.Failure, _i8.ProgressStats>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.ProgressStats>>);
}

/// A class which mocks [GetInstallCohortUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetInstallCohortUseCase extends _i1.Mock
    implements _i9.GetInstallCohortUseCase {
  MockGetInstallCohortUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, String?>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String?>>.value(
              _FakeEither_0<_i5.Failure, String?>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String?>>);
}

/// A class which mocks [CheckEntitlementUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckEntitlementUseCase extends _i1.Mock
    implements _i10.CheckEntitlementUseCase {
  MockCheckEntitlementUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i11.SubscriptionTier>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i11.SubscriptionTier>
                >.value(
                  _FakeEither_0<_i5.Failure, _i11.SubscriptionTier>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i11.SubscriptionTier>>);
}

/// A class which mocks [PurchaseProUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPurchaseProUseCase extends _i1.Mock
    implements _i12.PurchaseProUseCase {
  MockPurchaseProUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i11.SubscriptionTier>> call(
    String? packageId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [packageId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i11.SubscriptionTier>
                >.value(
                  _FakeEither_0<_i5.Failure, _i11.SubscriptionTier>(
                    this,
                    Invocation.method(#call, [packageId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i11.SubscriptionTier>>);
}

/// A class which mocks [RestorePurchasesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestorePurchasesUseCase extends _i1.Mock
    implements _i13.RestorePurchasesUseCase {
  MockRestorePurchasesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i11.SubscriptionTier>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i11.SubscriptionTier>
                >.value(
                  _FakeEither_0<_i5.Failure, _i11.SubscriptionTier>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i11.SubscriptionTier>>);
}
