// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/domain/usecases/join_shared_session_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pulse_coach/core/error/failures.dart' as _i5;
import 'package:pulse_coach/features/social/shared_session/domain/entities/shared_session.dart'
    as _i6;
import 'package:pulse_coach/features/social/shared_session/domain/repositories/shared_session_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SharedSessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedSessionRepository extends _i1.Mock
    implements _i3.SharedSessionRepository {
  MockSharedSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.SharedSession>> createSharedSession({
    required String? hostUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSharedSession, [], {
              #hostUserId: hostUserId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.SharedSession>>.value(
                  _FakeEither_0<_i5.Failure, _i6.SharedSession>(
                    this,
                    Invocation.method(#createSharedSession, [], {
                      #hostUserId: hostUserId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.SharedSession>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> refreshJoinCode({
    required String? sessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#refreshJoinCode, [], {#sessionId: sessionId}),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#refreshJoinCode, [], {
                  #sessionId: sessionId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> deleteSharedSession({
    required String? sessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSharedSession, [], {
              #sessionId: sessionId,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#deleteSharedSession, [], {
                  #sessionId: sessionId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.SharedSession>> joinSharedSession({
    required String? joinCode,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinSharedSession, [], {
              #joinCode: joinCode,
              #userId: userId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.SharedSession>>.value(
                  _FakeEither_0<_i5.Failure, _i6.SharedSession>(
                    this,
                    Invocation.method(#joinSharedSession, [], {
                      #joinCode: joinCode,
                      #userId: userId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.SharedSession>>);
}
