// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/features/daily_plan/generate_daily_plan_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pulse_coach/ai/engine/ai_engine.dart' as _i3;
import 'package:pulse_coach/core/error/failures.dart' as _i6;
import 'package:pulse_coach/features/daily_plan/domain/entities/daily_plan.dart'
    as _i7;
import 'package:pulse_coach/features/daily_plan/domain/repositories/daily_plan_repository.dart'
    as _i4;
import 'package:pulse_coach/features/onboarding/domain/entities/user_profile.dart'
    as _i15;
import 'package:pulse_coach/features/onboarding/domain/repositories/onboarding_repository.dart'
    as _i14;
import 'package:pulse_coach/features/session/domain/entities/activity_level.dart'
    as _i11;
import 'package:pulse_coach/features/session/domain/entities/health_data.dart'
    as _i9;
import 'package:pulse_coach/features/session/domain/repositories/health_repository.dart'
    as _i8;
import 'package:pulse_coach/features/session/domain/repositories/sensor_repository.dart'
    as _i10;
import 'package:pulse_coach/features/sessions_catalog/domain/entities/exercise.dart'
    as _i17;
import 'package:pulse_coach/features/sessions_catalog/domain/repositories/exercise_repository.dart'
    as _i16;
import 'package:pulse_coach/features/weather/domain/entities/weather_context.dart'
    as _i13;
import 'package:pulse_coach/features/weather/domain/repositories/weather_repository.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiEngineOutput_1 extends _i1.SmartFake
    implements _i3.AiEngineOutput {
  _FakeAiEngineOutput_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DailyPlanRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDailyPlanRepository extends _i1.Mock
    implements _i4.DailyPlanRepository {
  MockDailyPlanRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.DailyPlan?>> getPlanForDate(
    String? planDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanForDate, [planDate]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i7.DailyPlan?>>.value(
                  _FakeEither_0<_i6.Failure, _i7.DailyPlan?>(
                    this,
                    Invocation.method(#getPlanForDate, [planDate]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i7.DailyPlan?>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> savePlan(_i7.DailyPlan? plan) =>
      (super.noSuchMethod(
            Invocation.method(#savePlan, [plan]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#savePlan, [plan]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> deletePlanForDate(
    String? planDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlanForDate, [planDate]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#deletePlanForDate, [planDate]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [AiEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiEngine extends _i1.Mock implements _i3.AiEngine {
  MockAiEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.AiEngineOutput> call(_i3.AiEngineInput? input) =>
      (super.noSuchMethod(
            Invocation.method(#call, [input]),
            returnValue: _i5.Future<_i3.AiEngineOutput>.value(
              _FakeAiEngineOutput_1(this, Invocation.method(#call, [input])),
            ),
          )
          as _i5.Future<_i3.AiEngineOutput>);
}

/// A class which mocks [HealthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHealthRepository extends _i1.Mock implements _i8.HealthRepository {
  MockHealthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i9.HealthData>> fetchHealthData() =>
      (super.noSuchMethod(
            Invocation.method(#fetchHealthData, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i9.HealthData>>.value(
                  _FakeEither_0<_i6.Failure, _i9.HealthData>(
                    this,
                    Invocation.method(#fetchHealthData, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i9.HealthData>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> saveHealthData(
    _i9.HealthData? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveHealthData, [data]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#saveHealthData, [data]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [SensorRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSensorRepository extends _i1.Mock implements _i10.SensorRepository {
  MockSensorRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i11.ActivityLevel>>
  fetchActivityLevel() =>
      (super.noSuchMethod(
            Invocation.method(#fetchActivityLevel, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i11.ActivityLevel>>.value(
                  _FakeEither_0<_i6.Failure, _i11.ActivityLevel>(
                    this,
                    Invocation.method(#fetchActivityLevel, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i11.ActivityLevel>>);
}

/// A class which mocks [WeatherRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRepository extends _i1.Mock implements _i12.WeatherRepository {
  MockWeatherRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i13.WeatherContext>>
  getWeatherContext() =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherContext, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i13.WeatherContext>>.value(
                  _FakeEither_0<_i6.Failure, _i13.WeatherContext>(
                    this,
                    Invocation.method(#getWeatherContext, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i13.WeatherContext>>);
}

/// A class which mocks [OnboardingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnboardingRepository extends _i1.Mock
    implements _i14.OnboardingRepository {
  MockOnboardingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> acceptDisclaimer() =>
      (super.noSuchMethod(
            Invocation.method(#acceptDisclaimer, []),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#acceptDisclaimer, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, bool>> isDisclaimerAccepted() =>
      (super.noSuchMethod(
            Invocation.method(#isDisclaimerAccepted, []),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, bool>>.value(
              _FakeEither_0<_i6.Failure, bool>(
                this,
                Invocation.method(#isDisclaimerAccepted, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, bool>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> saveProfile(
    _i15.UserProfile? profile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveProfile, [profile]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#saveProfile, [profile]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i15.UserProfile>> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i15.UserProfile>>.value(
                  _FakeEither_0<_i6.Failure, _i15.UserProfile>(
                    this,
                    Invocation.method(#getProfile, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i15.UserProfile>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> updateProfile(
    _i15.UserProfile? profile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [profile]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#updateProfile, [profile]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String?>> getInstallCohort() =>
      (super.noSuchMethod(
            Invocation.method(#getInstallCohort, []),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, String?>>.value(
              _FakeEither_0<_i6.Failure, String?>(
                this,
                Invocation.method(#getInstallCohort, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, String?>>);
}

/// A class which mocks [ExerciseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRepository extends _i1.Mock
    implements _i16.ExerciseRepository {
  MockExerciseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>> getExercisesByType(
    String? sessionType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExercisesByType, [sessionType]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i17.Exercise>>(
                    this,
                    Invocation.method(#getExercisesByType, [sessionType]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i17.Exercise>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i2.Unit>> syncCatalog() =>
      (super.noSuchMethod(
            Invocation.method(#syncCatalog, []),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i6.Failure, _i2.Unit>(
                this,
                Invocation.method(#syncCatalog, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i2.Unit>>);
}
