// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/features/daily_plan/regenerate_daily_plan_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pulse_coach/core/error/failures.dart' as _i5;
import 'package:pulse_coach/features/daily_plan/domain/entities/daily_plan.dart'
    as _i6;
import 'package:pulse_coach/features/daily_plan/domain/repositories/daily_plan_repository.dart'
    as _i3;
import 'package:pulse_coach/features/daily_plan/domain/usecases/generate_daily_plan.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DailyPlanRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDailyPlanRepository extends _i1.Mock
    implements _i3.DailyPlanRepository {
  MockDailyPlanRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.DailyPlan?>> getPlanForDate(
    String? planDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanForDate, [planDate]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.DailyPlan?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.DailyPlan?>(
                    this,
                    Invocation.method(#getPlanForDate, [planDate]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.DailyPlan?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> savePlan(_i6.DailyPlan? plan) =>
      (super.noSuchMethod(
            Invocation.method(#savePlan, [plan]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#savePlan, [plan]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deletePlanForDate(
    String? planDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlanForDate, [planDate]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deletePlanForDate, [planDate]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [GenerateDailyPlan].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenerateDailyPlan extends _i1.Mock implements _i7.GenerateDailyPlan {
  MockGenerateDailyPlan() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.DailyPlan>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.DailyPlan>>.value(
                  _FakeEither_0<_i5.Failure, _i6.DailyPlan>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.DailyPlan>>);
}
