// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/bloc/shared_session/shared_session_20_5_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pulse_coach/core/cloud/realtime_gateway.dart' as _i3;
import 'package:pulse_coach/core/error/failures.dart' as _i8;
import 'package:pulse_coach/core/utils/location_service.dart' as _i10;
import 'package:pulse_coach/features/social/friends/domain/entities/social_profile.dart'
    as _i12;
import 'package:pulse_coach/features/social/friends/domain/usecases/get_social_profile_use_case.dart'
    as _i11;
import 'package:pulse_coach/features/social/shared_session/domain/entities/broadcast_event.dart'
    as _i5;
import 'package:pulse_coach/features/social/shared_session/domain/entities/presence_state.dart'
    as _i6;
import 'package:pulse_coach/features/social/shared_session/domain/usecases/delete_shared_session_use_case.dart'
    as _i7;
import 'package:pulse_coach/features/social/shared_session/domain/usecases/refresh_join_code_use_case.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RealtimeGateway].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtimeGateway extends _i1.Mock implements _i3.RealtimeGateway {
  @override
  _i4.Stream<_i5.BroadcastEvent> get broadcastEvents =>
      (super.noSuchMethod(
            Invocation.getter(#broadcastEvents),
            returnValue: _i4.Stream<_i5.BroadcastEvent>.empty(),
            returnValueForMissingStub: _i4.Stream<_i5.BroadcastEvent>.empty(),
          )
          as _i4.Stream<_i5.BroadcastEvent>);

  @override
  _i4.Stream<_i6.PresenceState> get presenceUpdates =>
      (super.noSuchMethod(
            Invocation.getter(#presenceUpdates),
            returnValue: _i4.Stream<_i6.PresenceState>.empty(),
            returnValueForMissingStub: _i4.Stream<_i6.PresenceState>.empty(),
          )
          as _i4.Stream<_i6.PresenceState>);

  @override
  _i4.Future<void> joinChannel(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#joinChannel, [sessionId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> leaveChannel() =>
      (super.noSuchMethod(
            Invocation.method(#leaveChannel, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendBroadcast({
    required String? event,
    required Map<String, dynamic>? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendBroadcast, [], {
              #event: event,
              #payload: payload,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackPresence({
    required String? userId,
    String? displayHandle,
    bool? isHost = false,
    double? lat,
    double? lon,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackPresence, [], {
              #userId: userId,
              #displayHandle: displayHandle,
              #isHost: isHost,
              #lat: lat,
              #lon: lon,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> untrackPresence() =>
      (super.noSuchMethod(
            Invocation.method(#untrackPresence, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [DeleteSharedSessionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteSharedSessionUseCase extends _i1.Mock
    implements _i7.DeleteSharedSessionUseCase {
  @override
  _i4.Future<_i2.Either<_i8.Failure, _i2.Unit>> call({
    required String? sessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#sessionId: sessionId}),
            returnValue: _i4.Future<_i2.Either<_i8.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i8.Failure, _i2.Unit>(
                this,
                Invocation.method(#call, [], {#sessionId: sessionId}),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i8.Failure, _i2.Unit>>.value(
                  _FakeEither_0<_i8.Failure, _i2.Unit>(
                    this,
                    Invocation.method(#call, [], {#sessionId: sessionId}),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i8.Failure, _i2.Unit>>);
}

/// A class which mocks [RefreshJoinCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRefreshJoinCodeUseCase extends _i1.Mock
    implements _i9.RefreshJoinCodeUseCase {
  @override
  _i4.Future<_i2.Either<_i8.Failure, String>> call({
    required String? sessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#sessionId: sessionId}),
            returnValue: _i4.Future<_i2.Either<_i8.Failure, String>>.value(
              _FakeEither_0<_i8.Failure, String>(
                this,
                Invocation.method(#call, [], {#sessionId: sessionId}),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i8.Failure, String>>.value(
                  _FakeEither_0<_i8.Failure, String>(
                    this,
                    Invocation.method(#call, [], {#sessionId: sessionId}),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i8.Failure, String>>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i10.LocationService {
  @override
  _i4.Future<_i2.Either<_i8.Failure, (double, double)>>
  getCityLevelCoordinates() =>
      (super.noSuchMethod(
            Invocation.method(#getCityLevelCoordinates, []),
            returnValue:
                _i4.Future<_i2.Either<_i8.Failure, (double, double)>>.value(
                  _FakeEither_0<_i8.Failure, (double, double)>(
                    this,
                    Invocation.method(#getCityLevelCoordinates, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i8.Failure, (double, double)>>.value(
                  _FakeEither_0<_i8.Failure, (double, double)>(
                    this,
                    Invocation.method(#getCityLevelCoordinates, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i8.Failure, (double, double)>>);
}

/// A class which mocks [GetSocialProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSocialProfileUseCase extends _i1.Mock
    implements _i11.GetSocialProfileUseCase {
  @override
  _i4.Future<_i2.Either<_i8.SocialFailure, _i12.SocialProfile>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i8.SocialFailure, _i12.SocialProfile>
                >.value(
                  _FakeEither_0<_i8.SocialFailure, _i12.SocialProfile>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i8.SocialFailure, _i12.SocialProfile>
                >.value(
                  _FakeEither_0<_i8.SocialFailure, _i12.SocialProfile>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i8.SocialFailure, _i12.SocialProfile>>);
}
