// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/bloc/shared_session/shared_session_cancel_refresh_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pulse_coach/core/error/failures.dart' as _i5;
import 'package:pulse_coach/features/social/friends/domain/entities/social_profile.dart'
    as _i8;
import 'package:pulse_coach/features/social/friends/domain/usecases/get_social_profile_use_case.dart'
    as _i7;
import 'package:pulse_coach/features/social/shared_session/domain/usecases/delete_shared_session_use_case.dart'
    as _i3;
import 'package:pulse_coach/features/social/shared_session/domain/usecases/refresh_join_code_use_case.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DeleteSharedSessionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteSharedSessionUseCase extends _i1.Mock
    implements _i3.DeleteSharedSessionUseCase {
  MockDeleteSharedSessionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> call({
    required String? sessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#sessionId: sessionId}),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#call, [], {#sessionId: sessionId}),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}

/// A class which mocks [RefreshJoinCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRefreshJoinCodeUseCase extends _i1.Mock
    implements _i6.RefreshJoinCodeUseCase {
  MockRefreshJoinCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> call({
    required String? sessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#sessionId: sessionId}),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#call, [], {#sessionId: sessionId}),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
}

/// A class which mocks [GetSocialProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSocialProfileUseCase extends _i1.Mock
    implements _i7.GetSocialProfileUseCase {
  MockGetSocialProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.SocialFailure, _i8.SocialProfile>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.SocialFailure, _i8.SocialProfile>
                >.value(
                  _FakeEither_0<_i5.SocialFailure, _i8.SocialProfile>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.SocialFailure, _i8.SocialProfile>>);
}
