// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/bloc/shared_session/shared_session_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pulse_coach/core/cloud/realtime_gateway.dart' as _i2;
import 'package:pulse_coach/features/social/shared_session/domain/entities/broadcast_event.dart'
    as _i4;
import 'package:pulse_coach/features/social/shared_session/domain/entities/presence_state.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RealtimeGateway].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtimeGateway extends _i1.Mock implements _i2.RealtimeGateway {
  @override
  _i3.Stream<_i4.BroadcastEvent> get broadcastEvents =>
      (super.noSuchMethod(
            Invocation.getter(#broadcastEvents),
            returnValue: _i3.Stream<_i4.BroadcastEvent>.empty(),
            returnValueForMissingStub: _i3.Stream<_i4.BroadcastEvent>.empty(),
          )
          as _i3.Stream<_i4.BroadcastEvent>);

  @override
  _i3.Stream<_i5.PresenceState> get presenceUpdates =>
      (super.noSuchMethod(
            Invocation.getter(#presenceUpdates),
            returnValue: _i3.Stream<_i5.PresenceState>.empty(),
            returnValueForMissingStub: _i3.Stream<_i5.PresenceState>.empty(),
          )
          as _i3.Stream<_i5.PresenceState>);

  @override
  _i3.Future<void> joinChannel(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#joinChannel, [sessionId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> leaveChannel() =>
      (super.noSuchMethod(
            Invocation.method(#leaveChannel, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> sendBroadcast({
    required String? event,
    required Map<String, dynamic>? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendBroadcast, [], {
              #event: event,
              #payload: payload,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> trackPresence({
    required String? userId,
    String? displayHandle,
    bool? isHost = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackPresence, [], {
              #userId: userId,
              #displayHandle: displayHandle,
              #isHost: isHost,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> untrackPresence() =>
      (super.noSuchMethod(
            Invocation.method(#untrackPresence, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
