// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/bloc/backup_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_bloc/flutter_bloc.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:pulse_coach/core/error/failures.dart' as _i5;
import 'package:pulse_coach/features/auth/domain/usecases/backup_now_use_case.dart'
    as _i7;
import 'package:pulse_coach/features/auth/domain/usecases/disable_backup_use_case.dart'
    as _i6;
import 'package:pulse_coach/features/auth/domain/usecases/enable_backup_use_case.dart'
    as _i3;
import 'package:pulse_coach/features/auth/domain/usecases/is_backup_enabled_use_case.dart'
    as _i9;
import 'package:pulse_coach/features/auth/domain/usecases/restore_backup_use_case.dart'
    as _i8;
import 'package:pulse_coach/features/auth/presentation/bloc/auth_bloc.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EnableBackupUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnableBackupUseCase extends _i1.Mock
    implements _i3.EnableBackupUseCase {
  MockEnableBackupUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.BackupFailure, String>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.BackupFailure, String>>.value(
                  _FakeEither_0<_i5.BackupFailure, String>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.BackupFailure, String>>);
}

/// A class which mocks [DisableBackupUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDisableBackupUseCase extends _i1.Mock
    implements _i6.DisableBackupUseCase {
  MockDisableBackupUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.BackupFailure, _i2.Unit>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.BackupFailure, _i2.Unit>>.value(
                  _FakeEither_0<_i5.BackupFailure, _i2.Unit>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.BackupFailure, _i2.Unit>>);
}

/// A class which mocks [BackupNowUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupNowUseCase extends _i1.Mock implements _i7.BackupNowUseCase {
  MockBackupNowUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.BackupFailure, DateTime?>> call({
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#userId: userId}),
            returnValue:
                _i4.Future<_i2.Either<_i5.BackupFailure, DateTime?>>.value(
                  _FakeEither_0<_i5.BackupFailure, DateTime?>(
                    this,
                    Invocation.method(#call, [], {#userId: userId}),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.BackupFailure, DateTime?>>);
}

/// A class which mocks [RestoreBackupUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestoreBackupUseCase extends _i1.Mock
    implements _i8.RestoreBackupUseCase {
  MockRestoreBackupUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.BackupFailure, _i2.Unit>> call({
    required String? userId,
    required String? phrase,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#userId: userId, #phrase: phrase}),
            returnValue:
                _i4.Future<_i2.Either<_i5.BackupFailure, _i2.Unit>>.value(
                  _FakeEither_0<_i5.BackupFailure, _i2.Unit>(
                    this,
                    Invocation.method(#call, [], {
                      #userId: userId,
                      #phrase: phrase,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.BackupFailure, _i2.Unit>>);
}

/// A class which mocks [IsBackupEnabledUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsBackupEnabledUseCase extends _i1.Mock
    implements _i9.IsBackupEnabledUseCase {
  MockIsBackupEnabledUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [AuthBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthBloc extends _i1.Mock implements _i10.AuthBloc {
  MockAuthBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i10.AuthState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i11.dummyValue<_i10.AuthState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i10.AuthState);

  @override
  _i4.Stream<_i10.AuthState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i10.AuthState>.empty(),
          )
          as _i4.Stream<_i10.AuthState>);

  @override
  void add(_i10.AuthEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i10.AuthEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i10.AuthState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i10.AuthEvent>(
    _i12.EventHandler<E, _i10.AuthState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<_i10.AuthEvent, _i10.AuthState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(_i10.AuthEvent? event, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#onDone, [event, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void onChange(_i12.Change<_i10.AuthState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
