// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/bloc/friends_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pulse_coach/core/error/failures.dart' as _i5;
import 'package:pulse_coach/features/social/friends/domain/entities/friend_item.dart'
    as _i8;
import 'package:pulse_coach/features/social/friends/domain/entities/pending_requests.dart'
    as _i7;
import 'package:pulse_coach/features/social/friends/domain/entities/social_profile.dart'
    as _i6;
import 'package:pulse_coach/features/social/friends/domain/repositories/friends_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FriendsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFriendsRepository extends _i1.Mock implements _i3.FriendsRepository {
  MockFriendsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.SocialFailure, _i6.SocialProfile?>> searchByHandle(
    String? handle,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchByHandle, [handle]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.SocialFailure, _i6.SocialProfile?>
                >.value(
                  _FakeEither_0<_i5.SocialFailure, _i6.SocialProfile?>(
                    this,
                    Invocation.method(#searchByHandle, [handle]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.SocialFailure, _i6.SocialProfile?>>);

  @override
  _i4.Future<_i2.Either<_i5.SocialFailure, _i7.PendingRequests>>
  getPendingRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingRequests, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.SocialFailure, _i7.PendingRequests>
                >.value(
                  _FakeEither_0<_i5.SocialFailure, _i7.PendingRequests>(
                    this,
                    Invocation.method(#getPendingRequests, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.SocialFailure, _i7.PendingRequests>>);

  @override
  _i4.Future<_i2.Either<_i5.SocialFailure, List<_i8.FriendItem>>>
  getFriends() =>
      (super.noSuchMethod(
            Invocation.method(#getFriends, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.SocialFailure, List<_i8.FriendItem>>
                >.value(
                  _FakeEither_0<_i5.SocialFailure, List<_i8.FriendItem>>(
                    this,
                    Invocation.method(#getFriends, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.SocialFailure, List<_i8.FriendItem>>>);

  @override
  _i4.Future<_i2.Either<_i5.SocialFailure, _i2.Unit>> sendFriendRequest(
    String? addresseeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendFriendRequest, [addresseeId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.SocialFailure, _i2.Unit>>.value(
                  _FakeEither_0<_i5.SocialFailure, _i2.Unit>(
                    this,
                    Invocation.method(#sendFriendRequest, [addresseeId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.SocialFailure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.SocialFailure, _i2.Unit>> acceptRequest(
    String? friendshipId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#acceptRequest, [friendshipId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.SocialFailure, _i2.Unit>>.value(
                  _FakeEither_0<_i5.SocialFailure, _i2.Unit>(
                    this,
                    Invocation.method(#acceptRequest, [friendshipId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.SocialFailure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.SocialFailure, _i2.Unit>> declineRequest(
    String? friendshipId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#declineRequest, [friendshipId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.SocialFailure, _i2.Unit>>.value(
                  _FakeEither_0<_i5.SocialFailure, _i2.Unit>(
                    this,
                    Invocation.method(#declineRequest, [friendshipId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.SocialFailure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.SocialFailure, _i2.Unit>> removeFriend(
    String? friendshipId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeFriend, [friendshipId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.SocialFailure, _i2.Unit>>.value(
                  _FakeEither_0<_i5.SocialFailure, _i2.Unit>(
                    this,
                    Invocation.method(#removeFriend, [friendshipId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.SocialFailure, _i2.Unit>>);
}
