// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/bloc/leaderboard_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pulse_coach/core/error/failures.dart' as _i5;
import 'package:pulse_coach/features/social/leaderboard/data/rank_freeze_store.dart'
    as _i6;
import 'package:pulse_coach/features/social/leaderboard/domain/usecases/get_friends_leaderboard_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetFriendsLeaderboardUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFriendsLeaderboardUseCase extends _i1.Mock
    implements _i3.GetFriendsLeaderboardUseCase {
  MockGetFriendsLeaderboardUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<
    _i2.Either<
      _i5.Failure,
      List<({String displayHandle, bool isOwn, int totalPoints, String userId})>
    >
  >
  call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<
                  _i2.Either<
                    _i5.Failure,
                    List<
                      ({
                        String displayHandle,
                        bool isOwn,
                        int totalPoints,
                        String userId,
                      })
                    >
                  >
                >.value(
                  _FakeEither_0<
                    _i5.Failure,
                    List<
                      ({
                        String displayHandle,
                        bool isOwn,
                        int totalPoints,
                        String userId,
                      })
                    >
                  >(this, Invocation.method(#call, [])),
                ),
          )
          as _i4.Future<
            _i2.Either<
              _i5.Failure,
              List<
                ({
                  String displayHandle,
                  bool isOwn,
                  int totalPoints,
                  String userId,
                })
              >
            >
          >);
}

/// A class which mocks [RankFreezeStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockRankFreezeStore extends _i1.Mock implements _i6.RankFreezeStore {
  MockRankFreezeStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> setFrozenRank(int? rank) =>
      (super.noSuchMethod(
            Invocation.method(#setFrozenRank, [rank]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
