// Mocks generated by Mockito 5.4.6 from annotations
// in pulse_coach/test/bloc/progress_comparison_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pulse_coach/core/error/failures.dart' as _i5;
import 'package:pulse_coach/features/progress/domain/entities/progress_stats.dart'
    as _i9;
import 'package:pulse_coach/features/progress/domain/entities/session_history_entry.dart'
    as _i8;
import 'package:pulse_coach/features/progress/domain/repositories/progress_repository.dart'
    as _i7;
import 'package:pulse_coach/features/social/comparison/domain/entities/progress_comparison_entry.dart'
    as _i6;
import 'package:pulse_coach/features/social/comparison/domain/repositories/progress_comparison_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProgressComparisonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgressComparisonRepository extends _i1.Mock
    implements _i3.ProgressComparisonRepository {
  MockProgressComparisonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.SocialFailure, List<_i6.ProgressComparisonEntry>>>
  getFriendsProgress() =>
      (super.noSuchMethod(
            Invocation.method(#getFriendsProgress, []),
            returnValue:
                _i4.Future<
                  _i2.Either<
                    _i5.SocialFailure,
                    List<_i6.ProgressComparisonEntry>
                  >
                >.value(
                  _FakeEither_0<
                    _i5.SocialFailure,
                    List<_i6.ProgressComparisonEntry>
                  >(this, Invocation.method(#getFriendsProgress, [])),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.SocialFailure, List<_i6.ProgressComparisonEntry>>
          >);
}

/// A class which mocks [ProgressRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgressRepository extends _i1.Mock
    implements _i7.ProgressRepository {
  MockProgressRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.SessionHistoryEntry>>>
  getSessionHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getSessionHistory, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i8.SessionHistoryEntry>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i8.SessionHistoryEntry>>(
                    this,
                    Invocation.method(#getSessionHistory, []),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.Failure, List<_i8.SessionHistoryEntry>>
          >);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.ProgressStats>> getProgressStats() =>
      (super.noSuchMethod(
            Invocation.method(#getProgressStats, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i9.ProgressStats>>.value(
                  _FakeEither_0<_i5.Failure, _i9.ProgressStats>(
                    this,
                    Invocation.method(#getProgressStats, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.ProgressStats>>);
}
